### ISSUE TITLE
typo on site

### ISSUE THREAD

**Issue by Arithmomaniac** [tmenier/flurl-site#11]
Here: https://github.com/tmenier/flurl-site/blob/master/content/index.md
"To contribure content"

**Comment by Vort** [comment]
Also example for `Url.Combine(` here: https://github.com/tmenier/flurl-site/blob/master/content/docs/fluent-url.md misses `);`.

**Comment by tmenier** [comment]
thanks, sorry I missed this long ago. both fixes manually applied
